## Pre-commit setup
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Ensures that a file is either empty, or ends with one newline.
      - id: end-of-file-fixer

      # Remove trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  # Code style and formatting
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length, "120",
          --skip-string-normalization,
        ]

  # # Linting and PEP-8
  # - repo: https://github.com/pycqa/flake8
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  #       args: ["--ignore=D400,E501", "--exclude=*test*"]
  #       additional_dependencies:
  #         - flake8-docstrings~=1.6.0

  # Security and Vulnerability checks
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [--skip, "B101", --recursive, clumper]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
